- name: breaking
  description: Requires breaking backwards compatibility
  color: ba68c8
- name: bug
  description: Something is borken
  color: e57373
- name: build
  description: Build or CI process
  color: dce775
- name: dependencies
  description: Pull requests that update a dependency file
  color: dce775
- name: documentation
  description: Documentation changes
  color: dce775
- name: enhancement
  description: Make a feature better
  color: 64b5f6
- name: feature
  description: A new feature!
  color: 81c784
- name: good first issue
  description: Something not too complex
  color: ffd54f
- name: Hacktoberfest
  description: Good first issue for Hacktoberfest
  color: 9c4668
- name: help wanted
  description: ""
  color: ffd54f
- name: performance
  description: An enhancement or problem with performance
  color: 64b5f6
- name: security
  description: A security concern or vulnerability
  color: e57373
- name: upstream
  description: Caused by an upstream dependency
  color: f7ae7e

# meta
- name: blocked
  description: ""
  color: e0e0e0
- name: duplicate
  description: ""
  color: e0e0e0
- name: invalid
  description: ""
  color: e0e0e0
- name: wontfix
  description: ""
  color: e0e0e0

# platforms
- name: linux
  description: Linux-specific issue
  color: a1887f
- name: macos
  description: macOS-specific issue
  color: a1887f
- name: windows
  description: Windows-specific issue
  color: a1887f
