[package]
name = "chttp"
version = "0.1.5"
description = "The practical HTTP client that is fun to use."
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
license = "MIT"
keywords = ["http", "request", "client"]
categories = ["web-programming::http-client"]
repository = "https://github.com/sagebind/chttp"

[features]
default = []

[dependencies]
bytes = "0.4"
futures-preview = "0.2"
http = "0.1"
lazy_static = "1"
lazycell = "1.0"
log = "0.4"
slab = "0.4"

[dependencies.curl]
git = "https://github.com/alexcrichton/curl-rust"

[dependencies.json]
version = "0.11"
optional = true

[target.'cfg(unix)'.dependencies]
nix = "0.11"

[dev-dependencies]
env_logger = "0.5"
rouille = "2.1"
