on: push

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - run: cargo test --features psl -- --test-threads=8
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: warn

      - run: cargo run --release --example simple
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: warn

  test-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - uses: docker://rustlang/rust:nightly
        args: cargo test --features psl,nightly -- --test-threads=8
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: warn
