name: ci
on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: isahc=debug
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - run: |
          sudo apt update
          sudo apt install -y libkrb5-dev
        if: matrix.os == 'ubuntu-latest'

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.45.0"
          default: true

      - run: cargo test --features cookies,psl,spnego,unstable-interceptors

      - run: cargo run --release --example simple

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true

      - name: Generate code coverage report
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: "-p isahc --run-types Doctests Tests --features cookies,psl"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
