name: ci
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: isahc=debug
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - run: |
          sudo apt update
          sudo apt install libkrb5-dev
        if: matrix.os == 'ubuntu-latest'

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.39.0"
          default: true

      - run: cargo test --features cookies,psl,spnego

      - run: cargo run --release --example simple

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - run: |
          sudo apt update
          sudo apt install libkrb5-dev
        if: matrix.os == 'ubuntu-latest'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features cookies,psl,spnego --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads'

      - uses: actions-rs/grcov@v0.1
