name: ci
on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
      RUST_LOG: isahc=debug
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - run: |
          sudo apt update
          sudo apt install libkrb5-dev
        if: matrix.os == 'ubuntu-latest'

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.39.0"
          default: true

      - run: cargo test --features cookies,psl,spnego

      - run: cargo run --release --example simple

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features cookies,psl --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads'

      - name: Install grcov
        run: |
          curl -LSs https://github.com/mozilla/grcov/releases/download/v0.5.9/grcov-linux-x86_64.tar.bz2 | tar xjf - -C /usr/local/bin

      - uses: actions-rs/grcov@v0.1

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.info
