name: ci
on: push

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Install Rust (macOS)
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.36.0
          echo "source $HOME/.cargo/env" >> $HOME/.bashrc
        if: runner.os == 'macOS'

      - run: rustup default 1.36.0

      - run: cargo test --features psl -- --test-threads=8
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: warn

      - run: cargo run --release --example simple
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: warn

  test-nightly:
    runs-on: ubuntu-latest
    container: rustlang/rust:nightly
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - run: cargo test --features psl,nightly -- --test-threads=8
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: warn
